name:                tipBot
version:             0.1.0.0
github:              "githubuser/tipBot"
license:             BSD3
author:              "Ruben Lenz"
maintainer:          "Ruben.Lenz@campus.lmu.de"
copyright:           "Creative Commons Attribution 4.0 International License (http://creativecommons
.org/licenses/by/4.0/)"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tipBot#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- aeson
- text
- bytestring
- vector
- transformers

library:
  source-dirs: src

executables:
  tipBot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tipBot
    default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - RecordWildCards

tests:
  tipBot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tipBot
    default-extensions:
    - OverloadedStrings
    - DeriveGeneric
    - RecordWildCards
